name: Deploy to GCP VM

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.GCP_VM_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Deploy files
      run: |
        ssh -o StrictHostKeyChecking=no USER@EXTERNAL_IP "
          cd ~/Admin_backend &&
          git pull origin main &&
          npm install --force &&
          pm2 restart all || pm2 start index.js
        "
